project:
  type: website

website:
  title: "Workshop Notes"
  navbar:
    left:
      - intermediate-git.qmd
      - intermediate-python.qmd
      - debugging/intro.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
